# TOTEM — board-specific settings (from the canonical zmk-config-totem).

# increase bluetooth signal power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# enable deep sleep support
CONFIG_ZMK_SLEEP=y

# the keyboard disconnects from bluetooth.
# uses very little power, but it may take
# a few seconds to reconnect after waking.
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

# Tune bluetooth profiles for quick select
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

# "Eager Debouncing" — trying to lower the input lag.
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# increase combo count per key for combo shifting
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=16
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=5

# add Experimental Features
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# Peripheral battery status
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
